# Generated by Django 2.1.1 on 2018-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='backend',
            field=models.TextField(choices=[('ustc', '中国科学技术大学'), ('zju', '浙江大学'), ('nju', '南京大学'), ('njust', '南京理工大学'), ('hnu', '湖南大学'), ('uestc', '电子科学技术大学'), ('email', '其他')], db_index=True),
        ),
    ]
