# Generated by Django 2.1.2 on 2018-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_auto_20181004_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='backend',
            field=models.TextField(choices=[('ustc', '中国科学技术大学'), ('zju', '浙江大学'), ('nju', '南京大学'), ('njust', '南京理工大学'), ('hnu', '湖南大学'), ('uestc', '电子科学技术大学'), ('sjtu', '上海交通大学'), ('eduemail', '其他高校'), ('email', '其他')], db_index=True),
        ),
    ]
