# Generated by Django 2.1.12 on 2019-10-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
