# Generated by Django 2.1.12 on 2019-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191010_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.TextField(null=True),
        ),
    ]
