# Generated by Django 2.1.12 on 2019-10-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191011_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
