# Generated by Django 3.1.2 on 2020-10-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191011_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': [('full', '管理个人信息'), ('view_ustc', '查看中国科学技术大学个人信息'), ('view_zju', '查看浙江大学个人信息'), ('view_hit', '查看哈尔滨工业大学个人信息'), ('view_xjtu', '查看西安交通大学个人信息'), ('view_cqu', '查看重庆大学个人信息'), ('view_bupt', '查看北京邮电大学个人信息'), ('view_jlu', '查看吉林大学个人信息'), ('view_neu', '查看东北大学个人信息'), ('view_nuaa', '查看南京航空航天大学个人信息')]},
        ),
    ]
