# Generated by Django 3.1.2 on 2020-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201019_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aff',
            field=models.TextField(null=True),
        ),
    ]
