# Generated by Django 3.1.2 on 2020-10-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_aff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_user', models.IntegerField(null=True)),
                ('context_time', models.DateTimeField()),
                ('context_elevated', models.BooleanField()),
                ('user', models.IntegerField()),
                ('group', models.TextField()),
                ('nickname', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('sno', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('qq', models.TextField(null=True)),
                ('school', models.TextField(null=True)),
                ('grade', models.TextField(null=True)),
                ('aff', models.TextField(null=True)),
                ('token', models.TextField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
