# Generated by Django 3.2.15 on 2022-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='campus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='major',
            field=models.TextField(null=True),
        ),
    ]
