# Generated by Django 4.2.4 on 2023-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_add_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="suspicious_reason",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userlog",
            name="suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlog",
            name="suspicious_reason",
            field=models.TextField(null=True),
        ),
    ]
