# Generated by Django 4.2.4 on 2023-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_user_suspicious_user_suspicious_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspicious_ddl",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userlog",
            name="suspicious_ddl",
            field=models.DateTimeField(null=True),
        ),
    ]
