# Generated by Django 4.2.16 on 2024-10-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_update_groups_2024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="suspicious",
        ),
        migrations.RemoveField(
            model_name="user",
            name="suspicious_ddl",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="suspicious",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="suspicious_ddl",
        ),
    ]
