# Generated by Django 3.1 on 2020-08-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFirstBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField(verbose_name='最后一次更新榜单的时间')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SubChallengeFirstBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('correctness', models.BooleanField(default=False)),
                ('challenge_clear', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('sub_challenge_clear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.subchallenge')),
            ],
            options={
                'permissions': [('full', '管理提交记录'), ('view', '查看提交记录')],
                'default_permissions': (),
            },
        ),
    ]
