# Generated by Django 3.1 on 2020-08-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20200815_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0004_auto_20200815_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='challenge_clear',
        ),
        migrations.CreateModel(
            name='ChallengeClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='challengeclear',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_challenge_clear'),
        ),
    ]
