# Generated by Django 3.1 on 2020-08-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_init_auth_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': []},
        ),
    ]
