# Generated by Django 3.1 on 2020-08-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='challenge',
            field=models.ForeignKey(blank=True, help_text='为空则为一般公告', null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
    ]
