# Generated by Django 3.1 on 2020-08-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20200814_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'default_permissions': []},
        ),
    ]
