# Generated by Django 3.1 on 2020-09-08 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20200815_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
