# Generated by Django 3.1 on 2020-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200812_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchallenge',
            name='enabled',
            field=models.BooleanField(default=True, help_text='\n        设为无效的题目不会被看到，也不会产生任何分数。 将题目改为无效时，它产生的分数会被移除，但并不删除此前的提交记录。\n        将题目改为有效时，此前的提交记录会重新产生分数。\n        <em>注意：在比赛开始后修改此项信息会重算排行榜，产生较大开销。</em>\n        '),
        ),
        migrations.AlterField(
            model_name='subchallenge',
            name='name',
            field=models.TextField(blank=True, help_text='若只有一个子题则可不填'),
        ),
    ]
