# Generated by Django 2.1.12 on 2019-10-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'default_permissions': (), 'ordering': ['index'], 'permissions': [('full', '管理题目'), ('view', '查看题目')]},
        ),
    ]
