# Generated by Django 2.1.12 on 2019-10-10 16:44

from django.db import migrations, models
import server.challenge.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='file',
            field=models.FileField(null=True, upload_to=server.challenge.models.challenge_file_path),
        ),
    ]
