# Generated by Django 4.2.5 on 2023-09-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0002_auto_20191011_2116"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="url",
            new_name="url_orig",
        ),
        migrations.AddField(
            model_name="challenge",
            name="check_url_clicked",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ChallengeURLRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(db_index=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenge.challenge",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("challenge", "user")},
            },
        ),
    ]
