# Generated by Django 4.2.16 on 2024-10-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_rename_url_challenge_url_orig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="use_web_docker_manager",
            field=models.BooleanField(default=False),
        ),
    ]
