# Generated by Django 4.2.5 on 2023-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0003_rename_url_challenge_url_orig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="podzol_image_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="podzol_lifetime",
            field=models.IntegerField(null=True),
        ),
    ]
