# Generated by Django 2.1.12 on 2019-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Hackergame')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, default='Hackergame,CTF')),
                ('content', models.TextField(blank=True, default='<h1>Hackergame</h1>', help_text='会被放入 <code>div</code> 的 HTML')),
            ],
        ),
    ]
