# Generated by Django 3.1.2 on 2020-10-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frontend', '0003_page_js'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstcEligible',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('eligible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UstcSnos',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.account')),
                ('snos', models.TextField()),
            ],
        ),
    ]
