# Generated by Django 3.2.7 on 2021-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_ustceligible_ustcsnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='<h1>问与答</h1>', help_text='会被放入 <code>div</code> 的 HTML')),
            ],
        ),
    ]
