# Generated by Django 3.2.7 on 2021-10-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='会被放入 <code>div</code> 的 HTML')),
                ('js', models.TextField(blank=True, help_text='会被放入 <code>script</code> 的 JS')),
            ],
        ),
    ]
