# Generated by Django 4.2.5 on 2023-10-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("frontend", "0006_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", models.TextField()),
                ("content_type", models.CharField(default="学号", max_length=32)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialProfileUsedRecord",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="ustcsnos",
            name="account",
        ),
        migrations.DeleteModel(
            name="UstcEligible",
        ),
        migrations.DeleteModel(
            name="UstcSnos",
        ),
    ]
