# Generated by Django 4.2.16 on 2024-10-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0009_alter_accountlog_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidirectionalFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_id",
                    models.IntegerField(help_text="该反馈对应 Challenge 的 ID"),
                ),
                (
                    "contents",
                    models.TextField(help_text="反馈内容，最长 1024", max_length=1024),
                ),
                (
                    "submit_datetime",
                    models.DateTimeField(auto_now_add=True, help_text="反馈时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="反馈用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
