# Generated by Django 4.2.16 on 2024-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0010_unidirectionalfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="会被放入 <code>div</code> 的 HTML"
                    ),
                ),
            ],
        ),
    ]
