# Generated by Django 2.1.12 on 2019-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('note', models.TextField(null=True)),
            ],
            options={
                'permissions': [('full', '管理定时器')],
                'default_permissions': (),
            },
        ),
    ]
