# Generated by Django 3.1.2 on 2020-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='state',
            new_name='can_view_challenges',
        ),
        migrations.AddField(
            model_name='trigger',
            name='can_submit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='can_try',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
