# Generated by Django 3.2.15 on 2022-10-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_auto_20201012_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='can_update_profile',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
