# Generated by Django 2.1.12 on 2019-09-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField(blank=True)),
                ('sno', models.TextField(blank=True)),
                ('tel', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
            ],
        ),
    ]
