# Generated by Django 2.1.12 on 2019-09-12 04:23

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('profile', 'Profile')
    db_alias = schema_editor.connection.alias
    for u in User.objects.using(db_alias).all():
        Profile.objects.using(db_alias).get_or_create(user=u)


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
