# Generated by Django 2.1.12 on 2019-09-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(['''
create view ustc_first_blood as
    with q as (
        select cp.id as id, ctf_solve.user_id as user_id, max(ctf_solve.time) as time

        from ctf_solve inner join ctf_flag on ctf_solve.flag_id = ctf_flag.id
        inner join ctf_problem as cp on ctf_flag.problem_id = cp.id
        inner join otp_device on ctf_solve.user_id = otp_device.user_id

        where cp.is_open and otp_device.backend = 'ustc'

        group by cp.id, ctf_solve.user_id

        having count(*) = (select count(*) from ctf_flag as cf where cf.problem_id = cp.id)
    )
    select ctf_problem.name, first_blood from ctf_problem
    left join (
        select q.id as id, min(auth_user.username) as first_blood

        from q inner join auth_user on q.user_id = auth_user.id

        where q.time=(select min(q2.time) from q as q2 where q2.id=q.id)

        group by q.id
    ) as q2 on q2.id = ctf_problem.id
    order by ctf_problem."index";
        '''], reverse_sql=['''
drop view ustc_first_blood;
        ''']),
    ]
