# Generated by Django 2.1.2 on 2018-10-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Will be put into a div as HTML.')),
                ('begin', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agreed', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('replace', models.ManyToManyField(blank=True, help_text='When in effect, obsolete these.', related_name='replaced_by', to='terms.Terms')),
            ],
        ),
    ]
