# Generated by Django 2.1.2 on 2018-10-09 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='banned_terms', to=settings.AUTH_USER_MODEL),
        ),
    ]
