# Generated by Django 2.1.12 on 2019-10-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField(db_index=True)),
                ('challenge', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ChallengeFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.IntegerField()),
                ('group', models.TextField(db_index=True, null=True)),
                ('user', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FlagClear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField(db_index=True)),
                ('challenge', models.IntegerField(db_index=True)),
                ('flag', models.IntegerField()),
                ('time', models.DateTimeField(db_index=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FlagFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('group', models.TextField(db_index=True, null=True)),
                ('user', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FlagViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_index=True)),
                ('group', models.TextField()),
                ('category', models.TextField(db_index=True, null=True)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('challenge', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'permissions': [('full', '管理提交记录')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='flagviolation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='flagfirst',
            unique_together={('challenge', 'flag', 'group')},
        ),
        migrations.AddField(
            model_name='flagclear',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='challengefirst',
            unique_together={('challenge', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='challengeclear',
            unique_together={('user', 'challenge')},
        ),
        migrations.AlterUniqueTogether(
            name='flagclear',
            unique_together={('user', 'challenge', 'flag')},
        ),
    ]
