# Generated by Django 2.1.12 on 2019-10-07 10:40

from django.db import migrations, models

from server.user.interface import User
from server.context import Context


def set_group(apps, schema_editor):
    Submission = apps.get_model('submission', 'Submission')
    db_alias = schema_editor.connection.alias
    for obj in Submission.objects.using(db_alias).all():
        obj.group = User.get(Context(elevated=True), obj.user).group
        obj.save()


def unset_group(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20191005_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.TextField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_group, unset_group),
        migrations.AlterField(
            model_name='submission',
            name='group',
            field=models.TextField(),
        ),
    ]
