# Generated by Django 2.1.12 on 2019-10-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20191011_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flagviolation',
            old_name='flag',
            new_name='violation_flag',
        ),
        migrations.RenameField(
            model_name='flagviolation',
            old_name='user',
            new_name='violation_user',
        ),
    ]
