# Generated by Django 3.1.2 on 2020-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20191015_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengefirst',
            name='group',
            field=models.TextField(db_index=True, default='$all'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flagfirst',
            name='group',
            field=models.TextField(db_index=True, default='$all'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.TextField(db_index=True, default='$all'),
            preserve_default=False,
        ),
    ]
