# Generated by Django 4.2.5 on 2023-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0007_auto_20201022_1721"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flagviolation",
            name="violation_flag",
        ),
        migrations.AddField(
            model_name="flagviolation",
            name="reason",
            field=models.TextField(null=True),
        ),
    ]
